services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: prod
    environment:
      APP_ENV: production
      APP_DEBUG: "false"

  web:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/prod.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
